access_key              = ""
secret_key              = ""
ami                     = "ami-f9dd458a"
region                  = "eu-west-1"
availability_zone       = "eu-west-1a"
public_key              = ""
connection_user         = "ec2-user"
connection_key_file     = "./keys/server.pem"
key_name                = "server"

appserver_instance_type = "t2.micro"
appserver_instances     = "2"

nginx_instance_type     = "t2.micro"
nginx_instances         = "1"
