access_key              = "AKIAIPV34ZVGGBYD5Q4Q"
secret_key              = "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"
ami                     = "ami-f9dd458a"
region                  = "eu-west-1"
availability_zone       = "eu-west-1a"
public_key              = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvvjJPKe67l0KVVGrzii7JjDm2z5tbPj/n4MpvixnzYG9ZQcVk8sZeEHVymUECbDVGb+DMHQDR2Hj1eqk2LydpkB19UeuzDUt3DgUfu/JoWzQQbdD82CUYmuOHMXldJGxSfdkDhWLduA8IwCtZq0VzYGLvnBsy9LUPnzhLphuSKoKyeVqZBJ6qn/v8ZjruhS0A/VMad84fKoCIbRCNfUbOWBHsEtUwHGFFYRgg7b42U3SB7VMP/oeh8DQjWAkcRDF6a8NLVaMlwyhlBSXaHHDbem2O8nWvbFgTWLtLlTG/sNAAUrV3Km8fGr8gyCNevFUvBqY3PNQsKrqKkziOUG6z"
connection_user         = "ec2-user"
connection_key_file     = "./keys/server.pem"
key_name                = "server"

appserver_instance_type = "t2.micro"
appserver_instances     = "2"

nginx_instance_type     = "t2.micro"
nginx_instances         = "1"
